### ISSUE TITLE
about Conv1DTranspose

### ISSUE THREAD

**Issue by Ben-Yee** [ETSSmartRes/VAE-NILM#4]
Hello!
When I was learning from your code, I found a  "Conv1DTranspose" function implemented by youself in VAE_function.py.
Is there any potential problem when using the offical "Conv1DTranspose" function to upsamle the data?
I am confused.
Thanks in advance if you would like to answer my question.

![image](https://user-images.githubusercontent.com/75025377/148776865-1e5f08ea-16cb-4333-ba6f-0a6185cf30bb.png)

**Comment by ETSSmartRes** [comment]
Hello,

Since I was using Tensorflow 1.14, there was no official "Conv1DTranspose" available. But now, if you are using a more recent version of TensorFlow and the layer is available, it should work.

Antoine

**Comment by Ben-Yee** [comment]
> 

Thanks again for your reply!
