### ISSUE TITLE
About the batch size in config file

### ISSUE THREAD

**Issue by Ben-Yee** [ETSSmartRes/VAE-NILM#5]
Dishwasher_VAE.json  in  House 2，batch size was set to 16.  It don't match the number ( 32 )  in the original paper. A mistake?

**Comment by Ben-Yee** [comment]
Fridge_VAE.json has the same problem.

**Comment by ETSSmartRes** [comment]
Thank you for spotting this error. If I remember correctly, I used the values in the Article. These files may not have been updated.
