### ISSUE TITLE
When I try to run the VAE model it gives me multiple inputs error

### ISSUE THREAD

**Issue by Abdulrahman-Adel** [ETSSmartRes/VAE-NILM#7]
I didn't change any of the code but when I run the training it gives me this error

`ValueError: Layer "model" expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 1024, 1) dtype=float32>]`

could you tell me how can I solve it?

**Comment by ETSSmartRes** [comment]
Hello,

Here is the solution: [https://github.com/ETSSmartRes/VAE-NILM/issues/3#issuecomment-1004401499](https://github.com/ETSSmartRes/VAE-NILM/issues/3#issuecomment-1004401499)

Best,

**Comment by Abdulrahman-Adel** [comment]
Thank you for you fast replay
